name: "Bump version"

on:
  push:
    branches:
      - 'main'

jobs:

  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v4.0.2
        id: semver
        with:
          format: "${major}.${minor}.${patch}"
          tag_prefix: "v"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.semver.outputs.version }}
          prerelease: true
          title: ${{ steps.semver.outputs.version }}